### ISSUE TITLE
Please publish this in pub.dartlang.org

### ISSUE THREAD

**Issue by tejainece** [dart-atom/atom.dart#37]
Amazing library combining the best language for web of all time and best hack-able browser of all time.

Could this please be published on pub store, so it gets more usage and publicity?

Thanks!

**Comment by devoncarew** [comment]
I'll defer to @danrubel, since he's done much of the work on this package, but my 0.02:

We're building this largely for our own use (for the flutter and dartino tooling). We're currently pulling the package in as a git dependency (https://github.com/dart-atom/dartlang/blob/master/pubspec.yaml#L11), which anyone is free to do. You can even pull from a specific git commit, which means package consumers won't get random upstream (and potential breaking) changes.

If we publish it as a package, there's more expectation that this will be maintained and generally provided for use by the community. Currently, I have the bandwidth to write the package, but not to support the package :) Hope that makes sense, and thanks for the feedback!

**Comment by tejainece** [comment]
Ok. I am already using it for my Atom plugins. 

Found it luckily. Otherwise, I was going to make a wrapper on my own.

Thanks for the brilliant work!

**Comment by danrubel** [comment]
I'm glad it's useful to you. As Devon said, we will improve and maintain it for our own use and happy to have others both consume it and contribute to it, but we don't have the cycles to formally support it... thus we have not published it.

**Comment by tejainece** [comment]
Ok
